using System.Runtime.InteropServices;
using System.Text.Json.Serialization;

namespace Tavenem.Mathematics;

/// <summary>
/// A <see cref="JsonSerializerContext"/> for <c>Tavenem.Mathematics</c>
/// </summary>
[JsonSerializable(typeof(Matrix3x2<double>))]
[JsonSerializable(typeof(Matrix3x2<Half>))]
[JsonSerializable(typeof(Matrix3x2<float>))]
[JsonSerializable(typeof(Matrix3x2<NFloat>))]
[JsonSerializable(typeof(Matrix4x4<double>))]
[JsonSerializable(typeof(Matrix4x4<Half>))]
[JsonSerializable(typeof(Matrix4x4<float>))]
[JsonSerializable(typeof(Matrix4x4<NFloat>))]
[JsonSerializable(typeof(Plane<double>))]
[JsonSerializable(typeof(Plane<Half>))]
[JsonSerializable(typeof(Plane<float>))]
[JsonSerializable(typeof(Plane<NFloat>))]
[JsonSerializable(typeof(Quaternion<double>))]
[JsonSerializable(typeof(Quaternion<Half>))]
[JsonSerializable(typeof(Quaternion<float>))]
[JsonSerializable(typeof(Quaternion<NFloat>))]
[JsonSerializable(typeof(Vector2<double>))]
[JsonSerializable(typeof(Vector2<Half>))]
[JsonSerializable(typeof(Vector2<float>))]
[JsonSerializable(typeof(Vector2<NFloat>))]
[JsonSerializable(typeof(Vector3<double>))]
[JsonSerializable(typeof(Vector3<Half>))]
[JsonSerializable(typeof(Vector3<float>))]
[JsonSerializable(typeof(Vector3<NFloat>))]
[JsonSerializable(typeof(Vector4<double>))]
[JsonSerializable(typeof(Vector4<Half>))]
[JsonSerializable(typeof(Vector4<float>))]
[JsonSerializable(typeof(Vector4<NFloat>))]
[JsonSerializable(typeof(IShape<double>))]
[JsonSerializable(typeof(IShape<Half>))]
[JsonSerializable(typeof(IShape<float>))]
[JsonSerializable(typeof(IShape<NFloat>))]
[JsonSerializable(typeof(Capsule<double>))]
[JsonSerializable(typeof(Capsule<Half>))]
[JsonSerializable(typeof(Capsule<float>))]
[JsonSerializable(typeof(Capsule<NFloat>))]
[JsonSerializable(typeof(Cone<double>))]
[JsonSerializable(typeof(Cone<Half>))]
[JsonSerializable(typeof(Cone<float>))]
[JsonSerializable(typeof(Cone<NFloat>))]
[JsonSerializable(typeof(Cuboid<double>))]
[JsonSerializable(typeof(Cuboid<Half>))]
[JsonSerializable(typeof(Cuboid<float>))]
[JsonSerializable(typeof(Cuboid<NFloat>))]
[JsonSerializable(typeof(Cylinder<double>))]
[JsonSerializable(typeof(Cylinder<Half>))]
[JsonSerializable(typeof(Cylinder<float>))]
[JsonSerializable(typeof(Cylinder<NFloat>))]
[JsonSerializable(typeof(Ellipsoid<double>))]
[JsonSerializable(typeof(Ellipsoid<Half>))]
[JsonSerializable(typeof(Ellipsoid<float>))]
[JsonSerializable(typeof(Ellipsoid<NFloat>))]
[JsonSerializable(typeof(Frustum<double>))]
[JsonSerializable(typeof(Frustum<Half>))]
[JsonSerializable(typeof(Frustum<float>))]
[JsonSerializable(typeof(Frustum<NFloat>))]
[JsonSerializable(typeof(HollowSphere<double>))]
[JsonSerializable(typeof(HollowSphere<Half>))]
[JsonSerializable(typeof(HollowSphere<float>))]
[JsonSerializable(typeof(HollowSphere<NFloat>))]
[JsonSerializable(typeof(Line<double>))]
[JsonSerializable(typeof(Line<Half>))]
[JsonSerializable(typeof(Line<float>))]
[JsonSerializable(typeof(Line<NFloat>))]
[JsonSerializable(typeof(SinglePoint<double>))]
[JsonSerializable(typeof(SinglePoint<Half>))]
[JsonSerializable(typeof(SinglePoint<float>))]
[JsonSerializable(typeof(SinglePoint<NFloat>))]
[JsonSerializable(typeof(Sphere<double>))]
[JsonSerializable(typeof(Sphere<Half>))]
[JsonSerializable(typeof(Sphere<float>))]
[JsonSerializable(typeof(Sphere<NFloat>))]
[JsonSerializable(typeof(Torus<double>))]
[JsonSerializable(typeof(Torus<Half>))]
[JsonSerializable(typeof(Torus<float>))]
[JsonSerializable(typeof(Torus<NFloat>))]
[JsonSerializable(typeof(FloatRange))]
public partial class MathematicsSourceGenerationContext : JsonSerializerContext { }
